---
- name: Configurar Servidor Web Flask en AWS (Frontend)
  hosts: aws_web
  become: yes
  gather_facts: no
  vars:
    # Es la IP privada de la VM de Azure
    db_host: "{{ azure_private_ip }}" #irá al pipeline


  pre_tasks:
    # 1. Instalar Python 3.8 usando comandos ssh
    # Amazon Linux 2 usa amazon-linux-extras para versiones nuevas
    - name: Bootstrap Python 3.8 (Raw SSH)
      raw: "sudo amazon-linux-extras install python3.8 -y && sudo yum install -y python38-devel gcc"
      changed_when: false

    # Habilitar Nginx
    - name: Habilitar repositorio de Nginx
      raw: "sudo amazon-linux-extras enable nginx1"
      changed_when: false

    # 2. Ordenarle a Ansible que use el nuevo Python
    - name: Cambiar Python a 3.8
      set_fact:
        ansible_python_interpreter: /usr/bin/python3.8

    # 3. Recolectar datos activado
    - name: Recolectar Facts (Ahora que tenemos Python 3.8)
      setup:

  tasks:
    - name: 1. Instalar paquetes de sistema (Nginx, Python, Pip)
      yum: # Usamos yum porque Amazon Linux 2 es basado en RedHat
        name:
          - nginx
          - git
          - postgresql-devel # Necesario para compilar psycopg2
        state: present

    # Aseguramos tener pip
    - name: 1.1 Asegurar pip para Python 3.8
      shell: "python3.8 -m ensurepip --upgrade"
      changed_when: false

    - name: 2. Instalar librerías de Python (Modo directo)
      # Usar módulo shell para invocar a pip a través de py
      shell: "/usr/bin/python3.8 -m pip install flask gunicorn psycopg2-binary"

    - name: 3. Crear directorio de la aplicación
      file:
        path: /var/www/app
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: 4. Copiar código de la aplicación (App + Templates)
      # Ansible buscará en máquina local (../app) y lo subirá a la VM
      copy:
        src: "../app/" 
        dest: "/var/www/app/"
        owner: ec2-user
        group: ec2-user

    - name: 5. Configurar servicio Systemd para Gunicorn (Tu App)
      # Esto convierte script de Python en un servicio de fondo
      copy:
        dest: /etc/systemd/system/mi_app.service
        content: |
          [Unit]
          Description=Gunicorn instance to serve my app
          After=network.target

          [Service]
          User=ec2-user
          Group=nginx
          WorkingDirectory=/var/www/app
          # INYECCIÓN DE VARIABLES DE ENTORNO (SECRETS)
          Environment="DB_HOST={{ db_host }}"
          Environment="DB_NAME=nomina_db"
          Environment="DB_USER=app_user"
          Environment="DB_PASS={{ db_password }}"
          # Comando de arranque
          ExecStart=/usr/local/bin/gunicorn --workers 3 --bind unix:app.sock -m 007 app:app
          
          [Install]
          WantedBy=multi-user.target
      notify: Reiniciar App

    - name: 6. Configurar Nginx como Proxy Inverso
      # Redirige el tráfico del puerto 80 al socket de Gunicorn
      copy:
        dest: /etc/nginx/conf.d/mi_app.conf
        content: |
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_pass http://unix:/var/www/app/app.sock;
              }
          }
      notify: Reiniciar Nginx

    - name: 7. Asegurar permisos de Nginx

      file:
        path: /var/www/app
        mode: '0755'  # Permisos de lectura y o ejecución para otros
        state: directory

    - name: 8. Iniciar Nginx
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Reiniciar App
      systemd:
        name: mi_app
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes