name: 'Infrastructure Destruction'

on:
  workflow_dispatch:

jobs:
  destroy:
    name: 'Destroy Infrastructure'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # 1. Destruir Azure
    - name: Terraform Destroy (Azure)
      env:
        # Credenciales para borrar recursos en Azure
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        # Credenciales para leer el estado (.tfstate) desde el Bucket S3
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"
      run: |
        cd proyecto-AZURE
        ssh-keygen -t rsa -b 4096 -f id_rsa -N ""
        terraform init
        # Destruye usando variables dummy para evitar errores de validaci√≥n
        terraform destroy -auto-approve \
          -var="aws_vpn_ip_address=1.1.1.1" \
          -var="vpn_shared_key=${{ secrets.VPN_SHARED_KEY }}"

    # 2. Destruir AWS
    - name: Terraform Destroy (AWS)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"
      run: |
        cd aws
        terraform init
        terraform destroy -auto-approve \
          -var="vpn_shared_key=${{ secrets.VPN_SHARED_KEY }}" \
          -var="azure_vpn_public_ip=1.1.1.1" # Dummy IP
